import path from 'node:path';
import { test, expect } from '@playwright/test';

/**
 * LESSON 10 - Dialogs, new tabs, uploads and iframes
 * Read docs/lessons/10-dialogs-tabs-uploads-frames.md alongside this file.
 *
 * These four things trip up most newcomers, so they get their own page:
 * http://127.0.0.1:4173/playground.html
 */

test.describe('Lesson 10 - the awkward bits', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/playground.html');
  });

  test('dialogs: Playwright auto-dismisses unless you handle them', async ({ page }) => {
    // Register the handler BEFORE the action that opens the dialog.
    page.once('dialog', async (dialog) => {
      expect(dialog.type()).toBe('alert');
      expect(dialog.message()).toBe('Your session will expire in 5 minutes.');
      await dialog.accept();
    });

    await page.getByTestId('alert-button').click();
    await expect(page.getByTestId('dialog-result')).toHaveText('Alert acknowledged');
  });

  test('confirm: accept and dismiss are different test cases', async ({ page }) => {
    page.once('dialog', (dialog) => dialog.accept());
    await page.getByTestId('confirm-button').click();
    await expect(page.getByTestId('dialog-result')).toHaveText('Item deleted');

    page.once('dialog', (dialog) => dialog.dismiss());
    await page.getByTestId('confirm-button').click();
    await expect(page.getByTestId('dialog-result')).toHaveText('Deletion cancelled');
  });

  test('prompt: accept with a value', async ({ page }) => {
    page.once('dialog', (dialog) => dialog.accept('Priya'));
    await page.getByTestId('prompt-button').click();
    await expect(page.getByTestId('dialog-result')).toHaveText('Hello, Priya!');
  });

  test('new tab: catch the popup from the browser context', async ({ page, context }) => {
    const popupPromise = context.waitForEvent('page'); // start listening first
    await page.getByTestId('new-tab-link').click();

    const newTab = await popupPromise;
    await newTab.waitForLoadState();

    await expect(newTab).toHaveURL(/about\.html/);
    await expect(newTab.getByTestId('about-heading')).toHaveText('About QA Shop');

    // The original tab is untouched.
    await expect(page).toHaveURL(/playground\.html/);
    await newTab.close();
  });

  test('file upload from disk', async ({ page }) => {
    const file = path.join(__dirname, '..', 'test-data', 'receipt.txt');
    await page.getByTestId('file-input').setInputFiles(file);

    await expect(page.getByTestId('upload-result')).toContainText('Uploaded: receipt.txt');

    // Clearing the selection.
    await page.getByTestId('file-input').setInputFiles([]);
    await expect(page.getByTestId('upload-result')).toHaveText('No file selected');
  });

  test('file upload from memory - no fixture file needed', async ({ page }) => {
    await page.getByTestId('file-input').setInputFiles({
      name: 'generated.txt',
      mimeType: 'text/plain',
      buffer: Buffer.from('generated by the test run'),
    });

    await expect(page.getByTestId('upload-result')).toContainText('generated.txt');
    await expect(page.getByTestId('upload-result')).toContainText('25 bytes');
  });

  test('iframes: reach inside with frameLocator', async ({ page }) => {
    const frame = page.frameLocator('[data-testid="support-frame"]');

    await expect(frame.getByTestId('frame-status')).toHaveText('Support is offline');
    await frame.getByRole('button', { name: 'Chat with support' }).click();
    await expect(frame.getByTestId('frame-status')).toHaveText('An agent will join shortly');

    // A locator on `page` cannot see inside the frame - a common source of
    // "element not found" confusion.
    await expect(page.getByTestId('frame-status')).toHaveCount(0);
  });

  test('screenshots of a page or a single element', async ({ page }, testInfo) => {
    // Attaching to the report is more useful than writing files nobody opens.
    await testInfo.attach('playground', {
      body: await page.screenshot({ fullPage: true }),
      contentType: 'image/png',
    });

    const dialogsCard = page.getByRole('heading', { name: '1. Browser dialogs' });
    await testInfo.attach('dialogs-heading', {
      body: await dialogsCard.screenshot(),
      contentType: 'image/png',
    });
  });
});
